# Generated by Django 5.0.6 on 2024-06-16 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caption_generated', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ImageDetail',
                'verbose_name_plural': 'ImageDetails',
                'db_table': 'imagedetails',
                'managed': True,
            },
        ),
    ]
